version: '3.4'
x-custom:
    shared_env: &shared_env
        AWS_KEY: ${AWS_ACCESS_KEY_ID}
        AWS_SECRET: ${AWS_SECRET_ACCESS_KEY}
services:
    web:
        image: nginx:latest
        privileged: true
        ports:
            - "7777:80"
        env_file:
            - ".env"
        volumes:
            - ./:/app
            - ./environment/nginx/app.conf:/etc/nginx/conf.d/default.conf
        links:
            - php

    php:
        build: ./environment/php-7
        privileged: true
        links:
            - redis
        ports:
            - "2221:22"
            - "35731:35729"
            - "9878:9876"
            - "8082:8080"
        env_file:
            - ".env"
        environment:
            PHP_IDE_CONFIG: "serverName=docker"
            <<: *shared_env
        volumes:
            - ./:/app
    redis:
        image: redis
        ports:
            - 6379:6379
        deploy:
            resources:
                limits:
                    memory: 1g